name: callisto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  firebase_core: ^3.3.0
  image_picker: ^0.8.7+4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  share_plus: ^6.3.0
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.6
  flutter_webrtc: ^0.11.6+hotfix.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.0.9
  web_socket_channel: ^3.0.1
  flutter_ffmpeg: ^0.4.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/logo.png
